// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using backend.Data.DBContext;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20240721065411_tags")]
    partial class tags
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.7");

            modelBuilder.Entity("backend.Model.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("StoreId")
                        .HasColumnType("TEXT");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("StoreId");

                    b.ToTable("Categorys");
                });

            modelBuilder.Entity("backend.Model.Entities.Store", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Stores");
                });

            modelBuilder.Entity("backend.Model.Entities.UserAuth", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("first_name")
                        .HasColumnType("TEXT");

                    b.Property<bool>("is_stuff")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("is_superUser")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("last_login")
                        .HasColumnType("TEXT");

                    b.Property<string>("last_name")
                        .HasColumnType("TEXT");

                    b.Property<string>("phone_number")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("email")
                        .IsUnique();

                    b.HasIndex("phone_number")
                        .IsUnique();

                    b.HasIndex("username")
                        .IsUnique();

                    b.ToTable("UsersAuths");
                });

            modelBuilder.Entity("backend.Model.Entities.Category", b =>
                {
                    b.HasOne("backend.Model.Entities.Store", "Store")
                        .WithMany("StoreTags")
                        .HasForeignKey("StoreId");

                    b.Navigation("Store");
                });

            modelBuilder.Entity("backend.Model.Entities.Store", b =>
                {
                    b.Navigation("StoreTags");
                });
#pragma warning restore 612, 618
        }
    }
}
